apiVersion: v1
kind: Service
metadata:
  name: product-catalog-v1-service
  namespace: product-catalog-v1
  labels:
    app: product-catalog
    version: v1.0
spec:
  selector:
    app: product-catalog
    version: v1.0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP 