server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vibe-monitor
    static_configs:
      - targets:
          - localhost
        labels:
          job: vibe-monitor
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: log
            container_name: attrs.container_name
      - match:
          selector: '{job="vibe-monitor"}'
          stages:
            - regex:
                expression: '.*vibe-monitor.*'
                action: keep
      - labels:
          level:
          container_name:
