version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: product-catalog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_catalog
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - product-network

  product-catalog:
    build: .
    container_name: product-catalog-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_catalog
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    depends_on:
      - mysql
    networks:
      - product-network
    restart: unless-stopped

volumes:
  mysql_data:


networks:
  product-network:
    driver: bridge
